sum up all occurrences when searching in multiple files
This is performed by running
    cat {} | grep {} | wc -l
instead of
    cat {} | grep -c {}

For example, calling file_contains_line_n_times on 'kea-legal*.txt'
now shows the total amount of occurences from all matched files.
Previously, it would fail with:

ValueError: invalid literal for int() with base 10: '/usr/local/var/lib/kea/kea-legal.20221018.txt:1\n/usr/local/var/lib/kea/kea-legal.20221019.txt:2'

The log functions have also been rewritten in the process